name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the workflow on a push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Hostgator
        run: |
          lftp -e "mirror -R build /public_html/greenthumbup.org; exit" \
          -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp.your-hostgator-domain.com
