name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}  # Replace with your FTP server
          username: ${{ secrets.FTP_USERNAME }}  # Replace with your FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # Replace with your FTP password
          local-dir: dist/assets/  # The directory containing your build files
          server-dir: public_html/  # The directory on the server where files should be uploaded


